app:
  mode: "mic"
  input_wav: ""
  mock: false
  sample_rate: 16000
  chunk_ms: 600
  src_lang: "en"
  dir: en-ru
resources:
  use_gpu: true
  threads: 6
vad:
  enabled: true
  threshold: 0.05
  min_speech_ms: 300
  min_silence_ms: 600
asr:
  engine: "whisper_ct2"
  model_path: "D:/CODE/translator-rt/models/whisper-medium-ct2"
  beam_size: 5
  lang_detect: false
  compute_type: "int8"
mt:
  engine: "marian"
  model_path: "D:/CODE/translator-rt/models/marian-ru-en"   # RU→EN
  model_path_back: "D:/CODE/translator-rt/models/marian-en-ru"   # EN→RU  (новое поле)
  max_src_tokens: 48
  segmenter:
    strategy: "fixed"
    max_words: 16
tts:
  engine: "piper"
  voices:
    ru: "D:/CODE/translator-rt/models/piper/ru/ru_RU-irina-medium.onnx"
    en: "D:/CODE/translator-rt/models/piper/en/en_GB-alan-medium.onnx"
  playback:
    device: null
    volume: 0.9
  piper:
    length_scale: 0.8
    noise_scale: 0.667
    noise_w: 0.8
logging:
  level: "INFO"
  dir: "logs"
  save_tts_wav: false
safety:
  prevent_feedback_loop: "ducking"
  ducking_db: -12

asr:
  engine: "faster-whisper"
  model_path: "D:/CODE/translator-rt/models/whisper-small-ct2"


